language: node_js
node_js:
  - 14.8.0
cache: npm

install:
  - npm ci

script:
  - npm test
  - npm run build

deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: main