language: node_js
node_js:
  - 14.8.1
cache: npm

before_install:
  - npm i -g npm@14.8.1

install:
  - npm ci

script:
  - npm test
  - npm run build


deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: main